# Install and load packages
if (!require("readr", quietly = TRUE))
  install.packages("readr")

if (!require("dplyr", quietly = TRUE))
  install.packages("dplyr")

if (!require("plyr", quietly = TRUE))
  install.packages("plyr", lib = "/usr/lib/R/library")

library(readr)

library(dplyr, quietly = TRUE)

library("plyr", quietly = TRUE)

print("Merging tables from all barcodes!")

# Function for using a copy database to adjust final copy number
weight_gene_copies <- function(otu_table, copies){
  #species_names <- otu_table$species
  #otu_table_16s_weighted <- otu_table[2:ncol(otu_table)]
  otu_table_16s_weighted <- otu_table
  for(row_num in 1:nrow(otu_table_16s_weighted)){
    species_name <- otu_table_16s_weighted["species"][row_num,]
    #print(species_name)
    if (species_name %in% copies$species) {
      #print(paste(species_name, "is present in copy database"))
      copy_number <- copies[copies$species == species_name,]$copies
      #print(copy_number)
      #print(otu_table_16s_weighted[row_num,])
      otu_table_16s_weighted[row_num,2:ncol(otu_table_16s_weighted)] <- otu_table_16s_weighted[row_num,2:ncol(otu_table_16s_weighted)]/copy_number
    }
    else{
      print(paste(species_name, "is not present in copy database"))
    }
  }
  return(otu_table_16s_weighted)
}

# Read arguments from console execution of R script
args <- commandArgs(trailingOnly = TRUE)
#print(args)

# Assign first argument to user_path. Where the result tables are.
user_path <- args[1]

copy_adjust <- args[2]

copy_db_path <- args[3]

# Initialize variables
abundance_tables <- list.files(path = user_path, pattern = "rel-abundance\\.tsv$", all.files = FALSE,
                                 full.names = FALSE, recursive = FALSE,
                                 ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

print(abundance_tables)

barcode_numbers <- c()

#Generate barcode names from abundance tables.
for (table in seq(from = 1, to = length(abundance_tables), by=1)) {
  # Using the characters of the barcode number of each abundance table file
  #current_bc <- substr(abundance_tables[table], start = 8, stop = 9)
  current_bc_string <- (strsplit(abundance_tables[table],split="_",fixed=T)[[1]][1])
  #print(current_bc_string)
  current_bc <- substr(current_bc_string, start = 8, nchar(current_bc_string))
  #print(abundance_tables[table])
  #print(strsplit(abundance_tables[table],split="_",fixed=T)[[1]][1])
  barcode_numbers <- c(barcode_numbers, current_bc)
#  if (substr(abundance_tables[table], start = 18, stop = 34) == "rel-abundance.tsv"){
#    barcode_numbers <- c(barcode_numbers, current_bc)
#  }
}

#print(barcode_numbers)

#print(length(abundance_tables))

processed_file = 1

# For loop to merge all the tables in the list, only using the tables that end with "rel-abundance.tsv" generated by emu.
for (file_number in seq(from = 1, to = length(abundance_tables), by=1)) {
  if (endsWith(abundance_tables[file_number], "rel-abundance.tsv")){
    #print(file_number)
    if(processed_file == 1){
      otu_table <- dplyr::select(readr::read_tsv(paste(user_path, abundance_tables[file_number], sep = "/")), "species", "estimated counts")
      colnames(otu_table) <- c("species", paste0("barcode", toString(barcode_numbers[processed_file])))
      otu_table <- plyr::ddply(otu_table, "species", plyr::numcolwise(sum))
      #print(otu_table)
      processed_file = processed_file + 1
    }
    else{
      current_table <- dplyr::select(readr::read_tsv(paste(user_path, abundance_tables[file_number], sep = "/")), "species", "estimated counts")
      colnames(current_table) <- c("species", paste0("barcode", toString(barcode_numbers[processed_file])))
      # Collapse rows that are the same species
      current_table <- plyr::ddply(current_table, "species", plyr::numcolwise(sum))
      #
      #print(current_table)
      processed_file = processed_file + 1
      #otu_table <- merge(otu_table, current_table, by="species", all = TRUE)
      #print(head(otu_table))
      otu_table <- dplyr::full_join(otu_table, current_table, by="species")
    }
  }
}

#print(otu_table)

otu_table["species"][is.na(otu_table["species"])] <- "Unassigned"

# Replace NAs with 0
otu_table[is.na(otu_table)] <- 0

# Collapse rows that are the same species
otu_table <- plyr::ddply(otu_table, "species", plyr::numcolwise(sum))
#otu_table <- ddply(otu_table, "species", numcolwise(sum))

write.table(otu_table, file = paste0(user_path, "/otu_table_unadjusted.csv"), quote = FALSE, row.names = FALSE, sep = ";")

if (copy_adjust == "TRUE" && !is.null(copy_db_path)) {
  print("Adjusting for copy numbers")
  copy_db <- read.csv(copy_db_path, sep=";")
  #print(head(copy_db))
  otu_table <- weight_gene_copies(otu_table, copy_db)
  write.table(otu_table, file = paste0(user_path, "/otu_table_adjusted.csv"), quote = FALSE, row.names = FALSE, sep = ";")
}

print(head(otu_table))
#print(otu_table)