# Install and load packages
if (!require("readr", quietly = TRUE))
  install.packages("readr")

if (!require("dplyr", quietly = TRUE))
  install.packages("dplyr")

library(readr)

library(dplyr, quietly = TRUE)

# Function for using a copy database to adjust final copy number
weight_gene_copies <- function(otu_table, copies){
  otu_table_16s_weighted <- otu_table
  for(row_num in 1:nrow(otu_table_16s_weighted)){
    if (rownames(otu_table_16s_weighted[row_num,]) %in% copies$species) {
      copy_number <- copies[copies$species == rownames(otu_table_16s_weighted[row_num,]),]$copies
      otu_table_16s_weighted[row_num,] <- otu_table_16s_weighted[row_num,]/copy_number
      #print(rownames(otu_table[row_num,]))
      #print(copies[copies$species == rownames(otu_table[row_num,]),]$copies)
      #print(otu_table[row_num,]/5)
    }
  }
  return(otu_table_16s_weighted)
}

# Read arguments from console execution of R script
args <- commandArgs(trailingOnly = TRUE)
#print(args)

# Assign first argument to user_path. Where the result tables are.
user_path <- args[1]

copy_adjust <- args[2]

copy_db_path <- args[3]

# Initialize variables
abundance_tables <- list.files(path = user_path, pattern = NULL, all.files = FALSE,
                                 full.names = FALSE, recursive = FALSE,
                                 ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)

#print(abundance_tables)

barcode_numbers <- c()

#Generate barcode names from abundance tables.
for (table in seq(from = 1, to = length(abundance_tables), by=1)) {
  # Using the last two characters of each abundance table file
  current_bc <- substr(abundance_tables[table], start = 8, stop = 9)
  if (substr(abundance_tables[table], start = 18, stop = 34) == "rel-abundance.tsv"){
    barcode_numbers <- c(barcode_numbers, current_bc)
  }
}

#print(barcode_numbers)

processed_file = 1

# For loop to merge all the tables in the list, only using the tables that end with "rel-abundance.tsv" generated by emu.
for (file_number in seq(from = 1, to = length(abundance_tables), by=1)) {
  if (endsWith(abundance_tables[file_number], "rel-abundance.tsv")){
    #print(file_number)
    if(processed_file == 1){
      otu_table <- dplyr::select(readr::read_tsv(paste(user_path, abundance_tables[file_number], sep = "/")), "species", "estimated counts")
      colnames(otu_table) <- c("species", paste0("barcode", toString(barcode_numbers[processed_file])))
      processed_file = processed_file + 1
    }
    else{
      current_table <- dplyr::select(readr::read_tsv(paste(user_path, abundance_tables[file_number], sep = "/")), "species", "estimated counts")
      colnames(current_table) <- c("species", paste0("barcode", toString(barcode_numbers[processed_file])))
      processed_file = processed_file + 1
      otu_table <- merge(otu_table, current_table, by="species", all = TRUE)
    }
  }
}

otu_table["species"][is.na(otu_table["species"])] <- "Unassigned"

# Replace NAs with 0
otu_table[is.na(otu_table)] <- 0

# Collapse rows that are the same species
otu_table <- plyr::ddply(otu_table, "species", plyr::numcolwise(sum))

if (copy_adjust && !is.null(copy_db_path)) {
  copy_db <- read.csv(copy_db_path, sep=";")
  otu_table <- weight_gene_copies(otu_table, copy_db)
}

print(head(otu_table))

write.table(otu_table, file = paste0(user_path, "/otu_table.csv"), quote = FALSE, row.names = FALSE, sep = ",")
